# Generated by Django 6.1.1 on 2026-09-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='0 dan 100 gacha, masalan 30'),
        ),
    ]
